# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run all

on:
  workflow_dispatch:
  push:
    paths:
    - 'config/**'

jobs:
  run-all:
    runs-on: ubuntu-latest
    env:
      INCLUDES_VERSION: 0
    steps:
    - uses: actions/setup-python@v2
      name: Set up Python 3.8
      with:
        python-version: 3.8
    - uses: actions/checkout@v2
    - name: Run ID generator
      run: |
        cd id-generator
        python main.py
        git add -f out
    - name: Run Flatbuf generator
      run: |
        cd flatbuf-generator
        python generate_schema.py
        python compile_schema.py --flatc bin/flatc
        git add -f out
    - name: Run Includes generator
      run: |
        cd includes-generator
        python main.py
        git add -f out
    - name: Push generated includes
      run: |
          git config --global user.name 'Automated CICD'
          git config --global user.email noreply@noone.com
          git add .
          git commit -am "Automatically generated files"
          git push
